language: generic
matrix:
  include:
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=4.2
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=5.0
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=5.1.1
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=https://swift.org/builds/swift-5.2.4-release/ubuntu1604/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu16.04.tar.gz
      - SWIFT_VERSION=5.2.4-RELEASE
    - os: osx
      osx_image: xcode10
      env:
      - SWIFT_DOWNLOAD_VERSION=4.2
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: osx
      osx_image: xcode10
      env:
      - SWIFT_DOWNLOAD_VERSION=5.0
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: osx
      osx_image: xcode11.2
      env:
      - SWIFT_DOWNLOAD_VERSION=5.1
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: osx
      osx_image: xcode11.5
      env:
      - SWIFT_DOWNLOAD_VERSION=https://swift.org/builds/swift-5.2.4-release/xcode/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-osx.pkg
      - SWIFT_VERSION=5.2.4-RELEASE
sudo: required
dist: xenial
install:
- git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$PATH"
- eval "$(swiftenv init -)"
- swiftenv install "$SWIFT_DOWNLOAD_VERSION"
- swift --version
script:
- ./script/test
after_success:
- bash <(curl -s https://codecov.io/bash)
