language: generic
matrix:
  include:
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=4.2
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: linux
      env:
      - SWIFT_DOWNLOAD_VERSION=https://swift.org/builds/swift-5.0-branch/ubuntu1404/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a-ubuntu14.04.tar.gz
      - SWIFT_VERSION=5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a
    - os: osx
      osx_image: xcode10
      env:
      - SWIFT_DOWNLOAD_VERSION=4.2
      - SWIFT_VERSION=$SWIFT_DOWNLOAD_VERSION
    - os: osx
      osx_image: xcode10
      env:
      - SWIFT_DOWNLOAD_VERSION=https://swift.org/builds/swift-5.0-branch/xcode/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a-osx.pkg
      - SWIFT_VERSION=5.0-DEVELOPMENT-SNAPSHOT-2019-02-23-a
sudo: required
dist: trusty
install:
- git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$PATH"
- eval "$(swiftenv init -)"
- swiftenv install "$SWIFT_DOWNLOAD_VERSION"
- swift --version
script:
- ./script/test
after_success:
- bash <(curl -s https://codecov.io/bash)
